### ISSUE TITLE
Last item in list is hidden behind bottom bar

### ISSUE THREAD

**Issue by jdckr** [astubenbord/paperless-mobile#22]
When filtering the last item of the list is partly hidden behind the bottom bar.
![Screenshot_20221114-211217](https://user-images.githubusercontent.com/40456550/201756861-25eaf8da-aed3-4f2c-b22d-b5faed9bd004.png)

**Comment by astubenbord** [comment]
which version do you have installed?

**Comment by astubenbord** [comment]
Should be fixed in the newest release 1.0.5-beta

**Comment by jdckr** [comment]
Better, but not fixed yet :-)
![Screenshot_20221115-061838](https://user-images.githubusercontent.com/40456550/201832737-b7f59917-67ed-460a-a75d-9ff8e96faf9d.png)

**Comment by astubenbord** [comment]
Hm that's weird, I'll have to do some more testing, I'll report back once I think it's fixed :)

**Comment by astubenbord** [comment]
can you try out the last release (https://github.com/astubenbord/paperless-mobile/releases/tag/v1.0.6-beta) and tell me if the issue still persists?

**Comment by jdckr** [comment]
When I just update the app it doesnt Start. A clean install cant commect to the server.

**Comment by jdckr** [comment]
False alarm. Clean install works. List is now also fine.
Thanks!

**Comment by astubenbord** [comment]
Great to hear!
