### ISSUE TITLE
[Bug]: App does not save changes 

### ISSUE THREAD

**Issue by Bluemeus** [astubenbord/paperless-mobile#331]
### What happened?

Hi,

after updating paperless-ngx from 1.17 to latest (2.1.3) i am not able to save document data. The save button is clicked, but nothing happend. If i leave after saving the title sometimes changes, even if i left the dialog by canceling after i tried to save.

I use a Xiaomi 9 Lite and a Lenovo Tab P11 Plus gen. 3 with the same behavior. Before updating paperless-ngx and the app everything worked fine and i apprecciate this cool and convinient app very well 

Document editing amd saving on the web is possible without problems.
I reinstalled the app, but nothing changes.

### Steps to reproduce

1. Open new or existing Document 
2. Do any changes
3. click save button 

### Log output from the app

```shell
2023-12-20 13:13:35.447	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to restore previous session...
2023-12-20 13:13:35.448	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Reading encrypted credentials...
2023-12-20 13:13:35.450	INFO    --- [                         ] -                          : Setting refresh rate to 60.000003814697266
2023-12-20 13:13:35.832	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Credentials successfully retrieved.
2023-12-20 13:13:35.832	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Updating security context...
2023-12-20 13:13:35.832	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Security context successfully updated.
2023-12-20 13:13:35.891	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Trying to update remote paperless user...
2023-12-20 13:13:35.891	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Trying to fetch API version...
2023-12-20 13:13:35.941	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).
2023-12-20 13:13:35.941	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Trying to update remote user object...
2023-12-20 13:13:36.148	DEBUG   --- [      AuthenticationCubit] - _updateRemoteUser        : Successfully updated remote user object.
2023-12-20 13:13:36.149	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Successfully updated remote paperless user.
2023-12-20 13:13:36.151	DEBUG   --- [      AuthenticationCubit] - restoreSession           : Previous session successfully restored.
2023-12-20 13:13:36.174	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2023-12-20 13:13:36.174	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2023-12-20 13:13:36.582	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2023-12-20 13:13:36.693	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
2023-12-20 13:13:36.694	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2023-12-20 13:13:36.907	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2023-12-20 13:13:38.233	DEBUG   --- [          LabelRepository] - findAllTags              : Loading all tags...
2023-12-20 13:13:38.567	DEBUG   --- [          LabelRepository] - findAllTags              : Successfully updated all tags.
2023-12-20 13:13:45.153	INFO    --- [        DocumentEditCubit] - loadFieldSuggestions     : Loading suggestions for document 508...
2023-12-20 13:13:45.459	INFO    --- [        DocumentEditCubit] - loadFieldSuggestions     : Found 3 suggestions for document 508.
2023-12-20 13:13:49.543	INFO    --- [        DocumentEditCubit] - updateDocument           : Updating document 508...
2023-12-20 13:13:51.064	INFO    --- [        DocumentEditCubit] - updateDocument           : Updating document 508...
2023-12-20 13:13:51.286	INFO    --- [        DocumentEditCubit] - updateDocument           : Updating document 508...
2023-12-20 13:13:51.463	INFO    --- [        DocumentEditCubit] - updateDocument           : Updating document 508...
2023-12-20 13:13:55.108	INFO    --- [        DocumentEditCubit] - updateDocument           : Updating document 508...
2023-12-20 13:14:06.176	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : Checking for new documents in inbox...
2023-12-20 13:14:06.355	INFO    --- [               InboxCubit] - refreshItemsInInboxCount : No new documents found in inbox.
```

### Paperless-ng*x Version

2.1.3

### Paperless-Mobile Version

3.1.5-59

### Device

Xiaomi 9 Lite (Android 10) and a Lenovo Tab P11 Plus gen. 3 (Android 13)

### Operating System Version

Android 10 / Android 13

### Device Locale

German

### Selected Locale

German

### Additional Context

I love this app! 😉👍

**Comment by Bluemeus** [comment]
Oh... i saw at this moment there was an update clearing this error. My re-i stallation was a few days ago, so you fixed the issue very quick. Thank you very much. Now everything works fine.

I gave a sponsoring about 25 usd for your very good work. i hope this will support your engagement. Keep it going! 😊

**Comment by Bluemeus** [comment]
Done.

**Comment by astubenbord** [comment]
Thanks man, really appreciate it :)

**Comment by epe** [comment]
Still happening with the latest mobile app.

Maybe some web socket issue to fix with nginx proxy settings?
