### ISSUE TITLE
[Bug]: Does not connect to my brand new Paperless-ngx

### ISSUE THREAD

**Issue by pypckompsite** [astubenbord/paperless-mobile#344]
### What happened?

The app does not connect to my paperless-ngx server on docker behind nginx proxy (Websockets enabled).
The server in publicly accesable.
The server URL is in form: https://paperless.DOMAIN.uk

When i click continue the app says "Nie udało się nawiązać połączenia z serwerem" (I got Polish locale, this translates to: Cant connect to the server). 

The server works perfectly in a browser, on the affected phone and on PC.
I have tried reinstalling the app both from play Store and from releases .apk file.

### Steps to reproduce

1. Install app
2. Paste in server url
3. Select PFX file
4. Paste password
5. Click 'Continue"
6. App cant connect

### Log output from the app

```shell
Pressing button does not generate logs
```

### Paperless-ng*x Version

2.2.1

### Paperless-Mobile Version

3.1.8

### Device

LG V60 EA

### Operating System Version

Android 12

### Device Locale

Poland

### Selected Locale

None

**Comment by astubenbord** [comment]
Hi, are you sure you are on paperless version 1.2.1? If this is the case (and you didn't mean 2.2.1), then I'll unfortunately have to tell you that this version is not supported anymore as it is just too old. Paperless has evolved quite a bit in the past months/years.

**Comment by pypckompsite** [comment]
Yep, its 2.2.1, sorry for the mistake

**Comment by astubenbord** [comment]
Did you set the PAPERLESS_URL Environment variable? Could you try to connect via IP (i.e. http://192.168...)?

**Comment by plankobostjan** [comment]
I'm experiencing the same issue as @pypckompsite after updating paperless-ngx to 2.3.0.

Trying to connect via IP does not solve the issue.

**Comment by reneherbrich** [comment]
I think these are different issues.

@plankobostjan: try clearing app data and setup paperless mobile again. The latest paperless-ngx version (2.3.0) now uses API v4, which seems to be unexpected for paperless mobile. After clearing data it falls back to v3 and you can login again.

`[      AuthenticationCubit] - _getApiVersion           : The server is running a newer API version (4) than the app supports (v3), falling back to latest supported version (v3). Warning: This might lead to unexpected behavior!
2024-01-07 12:17:46.273	DEBUG   --- [      AuthenticationCubit] - _getApiVersion           : Successfully retrieved API version (3).`

@astubenbord: found two additional issues.

1) when trying to connect via Cloudflare and MTLS I'm not able to login anymore. With an older version it was already working. When I'm at home and connect directly to my paperless-ngx server it's working fine.

Scenario 1 (Login at home -> disable wifi -> login via Cloudflare)
[paperless_mobile_logs_2024-01-07.log](https://github.com/astubenbord/paperless-mobile/files/13853203/paperless_mobile_logs_2024-01-07.log)

Scenario 2 (Clear data, Login via Cloudflare)
![Screenshot_20240107-122711](https://github.com/astubenbord/paperless-mobile/assets/61211636/cb49ab6c-5994-4c63-9e4f-4431348ba892)

2) when trying to save the logs after issue 1) I'm getting tons of error messages and the log will not be saved.
![Screenshot_20240107-122739](https://github.com/astubenbord/paperless-mobile/assets/61211636/f5e807f8-bc77-476b-aead-57cfa9b63231)
![Screenshot_20240107-122748](https://github.com/astubenbord/paperless-mobile/assets/61211636/373966b0-3df5-40a5-9c40-22c8435b054f)

**Comment by astubenbord** [comment]
@reneherbrich Thanks for the comprehensive report. I'll check and see what's going on.

**Comment by macrojames** [comment]
![Screenshot_20240107_172937.png](https://github.com/astubenbord/paperless-mobile/assets/482151/58b37992-9d71-431d-a5c0-974a573ee198)

Same here, my server is on 2.3.0, fresh install from yesterday. 
Toast message error saying Api 4 not supported.

**Comment by astubenbord** [comment]
@macrojames This issue should be resolved in the latest version (v3.2.0).

**Comment by macrojames** [comment]
> @macrojames This issue should be resolved in the latest version (v3.2.0).

Confirmed. Couldn't find anything like that in the change log.

Danke für deine App!

**Comment by astubenbord** [comment]
Yeah, it was under the "Some bug fixes" haha

Thanks, appreciate it :)

**Comment by astubenbord** [comment]
@reneherbrich There was indeed an issue with mTLS connections. Should hopefully be fixed in the next release.

**Comment by pypckompsite** [comment]
> @reneherbrich There was indeed an issue with mTLS connections. Should hopefully be fixed in the next release.

Thanks, for the quick fix. 

Great that v3.2.0 fixed the connection error.
mTLS still broken, thanks for finding and fixing in next release.

**Comment by reneherbrich** [comment]
@astubenbord that was fast - thank you. Will let you know, as soon as the next release is available.

**Comment by henningsieh** [comment]
I had the same issue with App Version 3.1.8 connecting to the latest server version 2.3.2.

"API 4 not supported..." 

App Version 3.2.0 fixed it! 🎉

**Comment by reneherbrich** [comment]
@astubenbord updated to 3.2.1 but issues mentioned earlier (mTLS and log writing loop) are still there. Logs look like the same as before.

[paperless_mobile_logs_2024-01-19.log](https://github.com/astubenbord/paperless-mobile/files/13986036/paperless_mobile_logs_2024-01-19.log)

**Comment by astubenbord** [comment]
Based on the log file it seems like there was a change in the API endpoint. I've noticed that the data type of the same property sometimes differs (e.g. the total file count reported from the statistics endpoint was reported as 0 if there were no documents yet and of object type including the file types if there was more than 1 document stored). These inconsistencies in the API specification can then lead to these errors which I do not catch since they are not expected. I'll have to try and reproduce this error to see when it occurs, and if what I mentioned is again the case I'll file a bug report to paperless-ngx.

**Comment by reneherbrich** [comment]
Made a mistake on my side, everything is working fine now - even with mTLS. Thanks!

**Comment by martin53757** [comment]
I have a similar issue. I'm trying to login to my paperless-ngx instance via an URL, not IP address ("https:///paperless.[Subdomain].[Domain].de"). Get the error message "host cannot be resolved. Please check server address and internet connection" (translated from German).

Paperless-NGX is hosted on Docker in my LAN. I use Traefik as a reverse proxy. Connection via IP when connected to LAN is working. Via Browser, too. All version are up to date (Server 2.6.0, App 3.2.1). I'm connection via Google OAuth2. Normal login is disabled.

**Comment by pdenessen** [comment]
Similar issue here: When I login from my wifi network to the IP address of the docker server then it works, but when I use my FQDN (Vial a cloudflare tunnel, then it comes in a loop and have I to kill the application (Paperless 2.6.2) app: 3.2.1+405

**Comment by MikeSchiessl** [comment]
I am running into the identical issue.

Paperless NGX: 2.14.7
Android App: 3.2.1

Entering a Connection URL:  https://ppl.my-domain.de
MTLS Certificate: in place

On my webserver, I am seeing the following message:
```
11.22.33.44 - - [03/Apr/2025:09:53:47 +0200] "GET /api/ HTTP/1.1" 400 208 "-" "Dart/3.2 (dart:io)"
```

so it seems the app wants to do a call (healthcheck ?) against the API, but (maybe due to the lack of using the MTLS CERT properly <-- just a guess) it gets a 400 

If I am calling the same web server without proper MTLS certificate in place (just using the browser) i am also getting a 400.
If i remove the "MTLS" certificate on my webserver (nginx), i am able to connect without any issue.


My best guess:
The Android app somehow tries to run a health check against an API endpoint without using the MTLS certificate provided, which leads to the "cannot connect to the server" issue

**Comment by astubenbord** [comment]
Hi @MikeSchiessl 
I'm not sure if this is related to a server or client side configuration issue. Did you get it sorted out by now? Back when I was still using MTLS on my instance, I didn't encounter these issues. The certificate should be provided. Maybe you can come back to this with the new version (which is not ready/released yet, but I'm adding the tag so you might be able to check once it's out)?

Thanks!

**Comment by neoscaler** [comment]
Same here with paperless-ngx 2.20.2 and paperless-mobile 3.2.1. My certificate works in Firefox, but as soon as I try to connect in paperless-mobile with PFX attached, I get "Could not connect to server" without any logs

**Comment by whacka** [comment]
This might be a different issue, but I got the same error message as https://github.com/astubenbord/paperless-mobile/issues/344#issuecomment-3669800972 when using mTLS. I am using OpenSSL version 3.5.4 and was able to resolve it by regenerating the PFX file using the "-legacy" option;
```
openssl pkcs12 -export -inkey cert.key -in cert.crt -out cert-legacy.pfx -legacy
```

before;
```
MAC: sha256, Iteration 2048
MAC length: 32, salt length: 8
PKCS7 Encrypted data: PBES2, PBKDF2, AES-256-CBC, Iteration 2048, PRF hmacWithSHA256
```
after;
```
MAC: sha1, Iteration 2048
MAC length: 20, salt length: 8
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
```
