### ISSUE TITLE
[Feature]: mpflanzer-allauth (OpenID Connect)

### ISSUE THREAD

**Issue by TheRealGramdalf** [astubenbord/paperless-mobile#374]
### Description

I've been taking part in https://github.com/paperless-ngx/paperless-ngx/pull/5190 recently, which adds OpenID Connect support (also known as OIDC, Social Login or Oauth2.0) via django-allauth. Though this has yet to be merged, I figured it was worth opening an issue sooner rather than later.

I'm unfortunately not super experienced with how OpenID implementations in mobile apps work, so I'm afraid I won't be much help there - but I'm more than happy to do any bug testing needed, since I already have my paperless instance running off the PR.

**Comment by TheRealGramdalf** [comment]
Related: (Most issues with SSO should be solved once people migrate to direct OpenID integration instead of reverse proxy/HTTP header auth)
https://github.com/astubenbord/paperless-mobile/issues/229
https://github.com/astubenbord/paperless-mobile/issues/240

**Comment by TheRealGramdalf** [comment]
There are preexisting libraries that could be used; a brief search brings the following results:

https://auth0.com/blog/get-started-with-flutter-authentication/
https://pub.dev/packages/openidconnect | [Github](https://github.com/4D-Technologies/openidconnect_flutter)
https://pub.dev/packages/openid_client | [Github](https://github.com/appsup-dart/openid_client)

**Comment by astubenbord** [comment]
A problem I still see is that the OAuth flow requires to communicate with the app through a callback. This may be possible, but during compile time, the app has no way of knowing your individual host name. However, to my understanding, an app has to declare the domain names it can open in the app's manifest, therefore each user would have to build the app from source and provide their host name in the android manifest. 
If this should not be the case, please correct me, but this is my current (and also rather limited) understanding of how OAuth works in a mobile context.

**Comment by zjean** [comment]
The app can register a fixed scheme like paperless:// which the auth provider will redirect to.
That will cause the call back to open the app.
In this way a user doesn't have to compile the app

**Comment by astubenbord** [comment]
Good point, thanks for clarifying!

**Comment by TheRealGramdalf** [comment]
The upstream PR has been ~~merged into the dev branch, but hasn't quite made it into a release~~ released - is there any chance this could be implemented along a similar timeline, or is it relatively complicated?

Not to try and put pressure on anyone, it would just be nice to know whether I should wait for this feature or just use alternative methods for now.

**Comment by astubenbord** [comment]
I don't think I'll be able to implement this right now. I see how it is very useful and I'll eventually also implement it for my hosted services as well, but at the moment, the app still has a lot of bugs which I have to prioritize.
If anyone is interested in implementing a solution, you are more than welcome to file a PR for this.

**Comment by beposec** [comment]
The URL recognition for paperless apps with OIDC login could be inspired by the Matrix protocol. With Matrix, the path of the OIDC provider (e.g. https://paperless.example.com/.well-known/paperless/oidc) is located on the domain in a .well-known directory.

https://areweoidcyet.com/client-implementation-guide/

**Comment by mentos1386** [comment]
Another potential ~solution~ workaround for this would be to use the api auth token (?). Instead of current form of "username & password" a form with "token" would could also be shown. That means that openid users can use the token authentication for now, until full openid flow is implemented.

I _guess_ that the api auth token works even with openid enabled on paperless?

Something like this was proposed for the proxy auth method [already](https://github.com/astubenbord/paperless-mobile/issues/154#issuecomment-1847200138), but in this case, it might actually work as there is no proxy involved to mess up the headers.

**Comment by AdmiralNemo** [comment]
Yes, it would be great if we could at least have the option to use an auth token directly instead of username and password.  This is a fairly common pattern for applications protected by Authelia or other proxy-based authentication solutions, and I think it would work well enough here.

**Comment by ghost** [comment]
Indeed, even a token based workaround would be great.

E: setting a password afterwards works too, but quite cumbersome.

**Comment by NikJen26** [comment]
I would also really appreciate this feature.
My current workaround is a "ingest" user to i can use the scanner function. This user has minimal permissions only so I can upload docs.

**Comment by nogweii** [comment]
I think native OIDC support in-app is probably too much to ask for, but supporting the API token auth could be a good fit. Users can enter their (admittedly long) token and successfully authenticate all `/api/` routes. Logging into the web UI would still be protected by Paperless-NGX's native OIDC support, but the API token would basically be an "app password".

@astubenbord do you think this plan would be a good short/medium term solution?

**Comment by lviss** [comment]
Here's how another flutter app implemented it (Immich) using a callback registered in the app: https://github.com/immich-app/immich/blob/da7a81b7525ad72bd92ab2ba434073a7b034e930/mobile/lib/services/oauth.service.dart#L6

**Comment by TheUltimateC0der** [comment]
Audiobookshelf also has OIDC Working in their App. Having one login for all selfhosted tools would make things so much easier. 

https://github.com/advplyr/audiobookshelf-app

**Comment by lex87-star** [comment]
is there any progress on implementing OIDC to Paperless-Mobile app. Right now not able to use it since depeding on Authentik. 
API Key feature would be be apprecaited for mittigation

**Comment by BlackWolfWoof** [comment]
I just switched to using Authentik, and thought of using 2FA too, as if OIDC is not implemented yet. Sadly 2FA doesn't seem to be implemented yet as well.
Implementing 2FA via TOTP would already be a good thing, then we would have a second factor authentication which works.
Also thanks for providing the app for all the years 🖤, i love it.

**Comment by lex87-star** [comment]
Oidc can be used via paperless_apps env var. Which is even kind of native. I have developed an mobile app but for other apps it is feasible to redirect the login to webpage/URL of the app.

**Comment by edmogeor** [comment]
For those wanting API key login (works with oidc accounts without a password) I've implemented here https://github.com/astubenbord/paperless-mobile/pull/530 if you want to build from my pr branch. Also implemented 2FA for an alternative protection method.

**Comment by TheRealGramdalf** [comment]
[Swift-paperless](https://github.com/paulgessinger/swift-paperless/issues/50) has OIDC support in the current testflight, it might be helpful to have as a working example. There were changes made in the paperless server which are required for swift-paperless to work properly, but I'm not sure if they made it into a release yet - in any case, just leaving a message here to let you know.

**Comment by astubenbord** [comment]
API Key login has been added [here](https://github.com/astubenbord/paperless-mobile/releases/tag/v4.2.0-apikey-auth-rc1), please give me feedback if it suits your needs and works as intended.

**Comment by ColorfulCookie** [comment]
I was looking for OIDC login support and stumbled upon the issue on the weekend -  personally I'm happy with this as a workaround, though proper support would of course be nicer from a security standpoint. It also worked perfectly first try, so no complaints

**Comment by Spiev** [comment]
@astubenbord 
> please give me feedback if it suits your needs and works as intended.

I installed the release. Logging in to my Paperless instance (which is secured via OIDC) with the API key worked without any problems! 👌 🙏

**Comment by lex87-star** [comment]
> [@astubenbord](https://github.com/astubenbord)
> 
> > please give me feedback if it suits your needs and works as intended.
> 
> I installed the release. Logging in to my Paperless instance (which is secured via OIDC) with the API key worked without any problems! 👌 🙏

Same here. Well appreciated

**Comment by TheRealGramdalf** [comment]
Same here, functioned perfectly for me without any server changes necessary. Very happy to finally have this as an option.

The only issue I ran into was that when the API key field was selected, it was hidden behind my keyboard - granted my keyboard of choice is likely taller than typical, but auto scrolling to keep the field visible would be much appreciated.

![ResizedImage_2026-03-11_14-33-53_5331[0].png](https://github.com/user-attachments/assets/be4db695-3f58-41ed-89de-7418deda481b)


A paste from clipboard button would also be a nice touch, since the paperless website has a copy to clipboard button for the API key. Not necessary by any means, but it would be a nice piece of polish if it's simple to do.

Thumbs up from me!
