### ISSUE TITLE
"You're offline" doesn't disappear

### ISSUE THREAD

**Issue by steinm** [astubenbord/paperless-mobile#54]
my wifi is a bit flaky, so my mobile phone often disconnects and reconnects. If that happens and the wifi is back, it often still says "You're offline". I can change the filter settings or the ordering and its updating the document list, but I cannot pull down the document list for updating it. The 'Labels' tab also claims that there is no internet connection and doesn't even try to update the 
Correspondents, Document Types, etc.

I have to quit the app and start it again to get out of that.

**Comment by steinm** [comment]
Here is how to reproduce it
1. open the app and turn off the internet connection, the app will tell you that you're offline
2. put the app into the background, e.g. by opening another app
3. turn on the internet connection again
4. switch back to your app -> it still say you're offline
5. turn the internet off and on while the app is in foreground -> it will recognize that you are online again
Looks to me like the app has to be in foreground to recognize whether the phone is online or offline

**Comment by astubenbord** [comment]
Should be fixed in [v1.4.1-beta](https://github.com/astubenbord/paperless-mobile/releases/tag/v1.4.1-beta).

**Comment by steinm** [comment]
Looks like 1.4.1-beta doesn't resolve it completely. I'm still seeing the red bar with 'you are offline', while the phone is actually online. I can set the filter, apply it and get a valid result. I just cannot select my saved views. The only way to get rid of it, is by restarting the app.

**Comment by astubenbord** [comment]
I see, this only appears when the connectivity changes while the app is not in the foreground, right? I'll check again

**Comment by astubenbord** [comment]
yeah, the app only listens to changes in connectivity when opened, if the State. changes outside it might not be registered by the listeners. should be easy to fix though

**Comment by steinm** [comment]
The message doesn't appear anymore in 2.0.1, but that is probably just related to the fact that it isn't displayed. The app itself still seems to have some internal online/offline flag. Sometimes the metadata or content tab still claims that there is no network connection, when there is a connection.

**Comment by astubenbord** [comment]
Okay, I will have a look the next days, I think that the logic is misplaced, it has to be done when the app is resumed again, the initState where it is currently located isn't always called when the app is resumed.

**Comment by astubenbord** [comment]
Okay, I will have a look the next days, I think that the logic is misplaced, it has to be done when the app is resumed again, the initState where it is currently located isn't always called when the app is resumed.
