### ISSUE TITLE
file upload with option "Created at" shows error

### ISSUE THREAD

**Issue by ChristophCaina** [astubenbord/paperless-mobile#72]
Hi,
Ich versuche eine Datei über das Smartphone hoch zuladen.
Dabei setze ich ein Datum bei "Ausgestellt am" - in Paperless-NGX kann diese Datei nicht verarbeitet werden.
Es wird folgende Fehlermeldung erzeugt:

```'str' object has no attribute 'utcoffset'```

Das Hochladen der Datei ohne "Ausgestellt am" option hingegen funktioniert (Ausgestellt am wird automatisch korrekt hinterlegt)

**Comment by astubenbord** [comment]
Hi, anscheinend erwartet Paperless ein Datum mit einem Z hinten (also UTC), ich schau mir das mal an und fixe das.

**Comment by astubenbord** [comment]
Related to #70

**Comment by astubenbord** [comment]
Which paperless version are you on? This seems to be related to https://github.com/paperless-ngx/paperless-ngx/issues/2019, however still get the same error on v1.11.3 (latest).

**Comment by ChristophCaina** [comment]
I'm using 1.11.3 ...

**Comment by astubenbord** [comment]
Okay, sorry but I guess we'll have to wait what the paperless team has to say. I'll publish an update with some more features/fixes and I've disabled the field for now with a hint.

**Comment by astubenbord** [comment]
@ChristophCaina Could you try to perform a POST form data request against your paperless server to /api/documents/post_document/ with the same values as I used here: https://github.com/paperless-ngx/paperless-ngx/issues/2435#issuecomment-1383221989 and tell me if it also results in the same error? Thanks

**Comment by ChristophCaina** [comment]
Submitting a file via the API page seems to work - but it did not use the Date I've added for "created" within the file.

I'Ve used the same date "2012-10-01" but it was added with todays date

Form submitted
![grafik](https://user-images.githubusercontent.com/26391061/212569722-984d0c1b-bdf4-4449-a7dd-54a1c0ab8617.png)

File appears in the list of documents:
![grafik](https://user-images.githubusercontent.com/26391061/212569756-36a34767-1406-4cb9-b7a0-325e46ea5ebd.png)

File information with today's date:
![grafik](https://user-images.githubusercontent.com/26391061/212569764-81386f38-b887-446c-a43b-dde05f0af0d0.png)

**Comment by ChristophCaina** [comment]
I did test it again with a different file - this also seems to work.
This time, I've selected another date - and the import did use the correct date from the file.

(used 2023-01-14, file date is 2020-11-17)

**Comment by astubenbord** [comment]
> Submitting a file via the API page seems to work - but it did not use the Date I've added for "created" within the file.
>
>I'Ve used the same date "2012-10-01" but it was added with todays date

I guess you left the "created" field empty here, right?

>I did test it again with a different file - this also seems to work.
>This time, I've selected another date - and the import did use the correct date from the file.
>
>(used 2023-01-14, file date is 2020-11-17)

I'm not sure I understand what you mean exactly. You POSTed the file (which has the created date 2020-11-17 in its metadata) and you also set the "created" field in the form data POST request to 2023-01-14? Which of both dates was then assigned by paperless?

**Comment by ChristophCaina** [comment]
sorry if my previous comment was unclear :-(

> I'Ve used the same date "2012-10-01" but it was added with todays date
I've used the 01.10.2012 as date for created - but paperless has then used today's date as meta information.

In the second case, paperless did use the file from the meta-data set in the file itself.

Here's another example - the file is from 2013 ...

1. selected and used created date 01.10.2012
![grafik](https://user-images.githubusercontent.com/26391061/212575769-c046e27a-8dda-4bcc-a67c-b46ccbe2bff1.png)

2 Uploaded successfully - right now it's showing "Ausgestellt am" with the current date & time
![grafik](https://user-images.githubusercontent.com/26391061/212575803-7e367bab-9f16-46e9-ab7f-8226aac42939.png)

3. File added - correct meta data information (created => April 2013)
![grafik](https://user-images.githubusercontent.com/26391061/212575838-75fcc37d-95a7-4b8c-9f1e-bf62f5d8f4aa.png)

Anyway: What I could not reproduce while using the API:
The error msg. regarding the UTC Offset

**Comment by astubenbord** [comment]
> Submitting a file via the API page seems to work - but it did not use the Date I've added for "created" within the file.
> 
> I'Ve used the same date "2012-10-01" but it was added with todays date
> 
> Form submitted
> ![grafik](https://user-images.githubusercontent.com/26391061/212569722-984d0c1b-bdf4-4449-a7dd-54a1c0ab8617.png)
> 
> File appears in the list of documents:
> ![grafik](https://user-images.githubusercontent.com/26391061/212569756-36a34767-1406-4cb9-b7a0-325e46ea5ebd.png)
> 
> File information with today's date:
> ![grafik](https://user-images.githubusercontent.com/26391061/212569764-81386f38-b887-446c-a43b-dde05f0af0d0.png)
> 

    Thanks for the clarification and no worries. Seems like a date format issue, as also confirmed and reproduced by the paperless-ngx maintainers. Thanks for your efforts

**Comment by astubenbord** [comment]
@ChristophCaina is this resolved in the newest version? Please let me know

**Comment by ChristophCaina** [comment]
Hi, could not test it yet... firt, I need a new file with which I can test this on my phone... I will let you know as soon as I tested this again.

**Comment by ChristophCaina** [comment]
Hi, seems not to work with the latest version.
I had to check, if I already got the latest version of the app, but still have the same message after uploading a file with a specific date given in the upload.

**Comment by ChristophCaina** [comment]
Hi, haven't recognized that there was an paperless-ngx update available.
I will test it with the updated version as soon as possible
