### ISSUE TITLE
[BUG] Cannot select suggested document-types when filtering

### ISSUE THREAD

**Issue by LUC4R4T0R** [astubenbord/paperless-mobile#83]
**Describe the bug**
When I try to select a doucment-type while filtering my documents a list with suggestions appears. If I try to select one of these suggestions, I am not able to interact with the list. Instead my interactions change the inputs beneath the list.

**To Reproduce**
1. Click on '[hopper icon]'
2. Click on 'Document type'
3. Select a suggestion
4. Nothing happens

**Expected behavior**
One specific document type gets selected.

**Screenshots**

https://user-images.githubusercontent.com/26312201/215320621-26f62ddf-e2c0-467c-98f5-e415facb8481.mp4

**Device Information:**
 - Device: Samsung Galaxy S21+
 - OS: Android 13
 - Paperless Mobile version 1.5.3
 - Paperless Server version 1.12.1

**Comment by astubenbord** [comment]
Might be related to #58

**Comment by davethehacker** [comment]
> Might be related to #58

I'pretty sure it is. Happens for all input suggestions, be it in filters or edit.

**Comment by astubenbord** [comment]
Yeah, this error should occur on all three document type, correspondent and storage path fields as they share the same logic. It would be very helpful if any of you could debug the app locally on a device where the error occurs because I cannot reproduce the error neither on an emulator nor on my physical device.

**Comment by blitzdose** [comment]
> Yeah, this error should occur on all three document type, correspondent and storage path fields as they share the same logic. 

But there is still a difference between correspondent and document type. The document type don't work at all and the correspondent only doesn't work, if there is text in the field. 

I will debug the app as soon as possible and send you the log / investigate the issue.

**Comment by astubenbord** [comment]
Thanks, this will be really helpful!

**Comment by blitzdose** [comment]
I opened the app, clicked the filter icon, and tried to select a document type. The log is below (But I don't think there is anything useful in that)

I also found an issue in the GitHub repo of the flutter_typeahead: https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/356
It looks exactly like this issue. I tried using the stable channel of flutter and dart as one person there suggested but the problem still persists. Sadly the developer closed the issue there with no comment. One person mentioned a FocusNode was the problem but I don't understand enough about Flutter to try that out. I removed all of the FocusNode Objects used near the Field but nothing happened. 

I hope some of the information helps. If you got something to try out just hit me up

```
2023-02-01 20:07:30.288  5760-5776  AppScoutStateMachine    de.astubenbord.paperless_mobile      D  5760-ScoutStateMachinecreated
2023-02-01 20:07:30.293  5760-5760  Compatibil...geReporter de.astubenbord.paperless_mobile      D  Compat change id reported: 171979766; UID 11299; state: ENABLED
2023-02-01 20:07:30.307  5760-5760  ziparchive              de.astubenbord.paperless_mobile      W  Unable to open '/data/app/~~RoQ-kawYj1Jt1q8wnYQmcA==/de.astubenbord.paperless_mobile-X0fF0GEAI1GVJ2fecBuUJQ==/base.dm': No such file or directory
2023-02-01 20:07:30.307  5760-5760  ziparchive              de.astubenbord.paperless_mobile      W  Unable to open '/data/app/~~RoQ-kawYj1Jt1q8wnYQmcA==/de.astubenbord.paperless_mobile-X0fF0GEAI1GVJ2fecBuUJQ==/base.dm': No such file or directory
2023-02-01 20:07:30.509  5760-5760  nativeloader            de.astubenbord.paperless_mobile      D  Configuring classloader-namespace for other apk /data/app/~~RoQ-kawYj1Jt1q8wnYQmcA==/de.astubenbord.paperless_mobile-X0fF0GEAI1GVJ2fecBuUJQ==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~RoQ-kawYj1Jt1q8wnYQmcA==/de.astubenbord.paperless_mobile-X0fF0GEAI1GVJ2fecBuUJQ==/lib/arm64:/data/app/~~RoQ-kawYj1Jt1q8wnYQmcA==/de.astubenbord.paperless_mobile-X0fF0GEAI1GVJ2fecBuUJQ==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/de.astubenbord.paperless_mobile
2023-02-01 20:07:30.520  5760-5760  Perf                    de.astubenbord.paperless_mobile      I  Connecting to perf service.
2023-02-01 20:07:30.524  5760-5760  GraphicsEnvironment     de.astubenbord.paperless_mobile      V  ANGLE Developer option for 'de.astubenbord.paperless_mobile' set to: 'default'
2023-02-01 20:07:30.524  5760-5760  GraphicsEnvironment     de.astubenbord.paperless_mobile      V  Neither updatable production driver nor prerelease driver is supported.
2023-02-01 20:07:30.529  5760-5760  ForceDarkHelperStubImpl de.astubenbord.paperless_mobile      I  initialize for de.astubenbord.paperless_mobile , ForceDarkOrigin
2023-02-01 20:07:30.531  5760-5760  OpenGLRenderer          de.astubenbord.paperless_mobile      D  JNI_OnLoad success
2023-02-01 20:07:30.531  5760-5760  MiuiForceDarkConfig     de.astubenbord.paperless_mobile      I  setConfig density:2.750000, mainRule:0, secondaryRule:0, tertiaryRule:0
2023-02-01 20:07:30.532  5760-5760  NetworkSecurityConfig   de.astubenbord.paperless_mobile      D  No Network Security Config specified, using platform default
2023-02-01 20:07:30.533  5760-5760  NetworkSecurityConfig   de.astubenbord.paperless_mobile      D  No Network Security Config specified, using platform default
2023-02-01 20:07:30.582  5760-5760  aperless_mobil          de.astubenbord.paperless_mobile      W  Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, allowed)
2023-02-01 20:07:30.582  5760-5760  aperless_mobil          de.astubenbord.paperless_mobile      W  Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->c:Ljava/util/Collection; (unsupported, reflection, allowed)
2023-02-01 20:07:30.582  5760-5760  aperless_mobil          de.astubenbord.paperless_mobile      W  Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, allowed)
2023-02-01 20:07:30.582  5760-5760  aperless_mobil          de.astubenbord.paperless_mobile      W  Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, allowed)
2023-02-01 20:07:30.605  5760-5760  ViewScrollStubImpl      de.astubenbord.paperless_mobile      D  the value of mScrollFrictionRes is: 0.015
2023-02-01 20:07:30.621  5760-5760  MiuiMultiWindowUtils    de.astubenbord.paperless_mobile      D  freeform resolution args raw data:{  "zizhan":{    "freeform_args": {      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.168,"left_margin":0.484},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.5643,"original_scale":0.74,"top_margin":0.1222,"left_margin":0.59745},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.2596,"left_margin":0.2624},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.604,"top_margin":0.213,"left_margin":0.3758}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.74,"top_margin":0.0753,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":1,"original_scale":0.5756,"top_margin":-1,"left_margin":0.0753},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":0.0753,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6847,"original_scale":0.587,"top_margin":-1,"left_margin":0.0753}}    },    "mini_freeform_args":{      "inner":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.147},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.165},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.165}      },      "outer":{        "vertical_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "horizontal_portrait":{"aspect_ratio":0.626, "original_ratio":0.26},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.293},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.293}}    }  },  "wide_default":{    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":0.125,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.625, "original_ratio":0.58,"original_scale":0.7574,"top_margin":-1,"left_margin":0.0714},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":0.125,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":1,"original_scale":0.5153,"top_margin":-1,"left_margin":0.0714}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.144},        "vertical_landscape":{"aspect_ratio":-1, "original_ratio":0.144},        "horizontal_landscape":{"aspect_ratio":-1, "original_ratio":0.144}    }  },  "narrow_default": {    "freeform_args": {        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":1,"original_scale":0.7182,"top_margin":0.142,"left_margin":-1},        "horizontal_portrait":{"aspect_ratio":0.8, "original_ratio":1,"original_scale":0.7182,"top_margin":-1,"left_margin":0.05},        "vertical_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":0.142,"left_margin":-1},        "horizontal_landscape":{"aspect_ratio":1.6, "original_ratio":0.6545,"original_scale":0.4473,"top_margin":-1,"left_margin":0.05}    },    "mini_freeform_args":{        "vertical_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "horizontal_portrait":{"aspect_ratio":0.5625, "original_ratio":0.3},        "vertical_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3},        "horizontal_landscape":{"aspect_ratio":1.7778, "original_ratio":0.3}    }  },  "regular_default": {    "freeform_args": {      "vertical_portrait":{"aspect_ratio":0.625, "original_ratio":1,"original_scale":0.7,"top_margin":0.109,"left_margin":-1},      "horizontal_portrait":{"aspect_ratio":0.6667, "original_ratio":1,"original_scale":0.6102,"top_margin":-1,"left_margin":0.026},      "vertical_landscape":{"aspect_ratio
2023-02-01 20:07:30.634  5760-5760  IS_CTS_MODE             de.astubenbord.paperless_mobile      D  false
2023-02-01 20:07:30.634  5760-5760  MULTI_WIND...CH_ENABLED de.astubenbord.paperless_mobile      D  false
2023-02-01 20:07:30.637  5760-5760  IS_CTS_MODE             de.astubenbord.paperless_mobile      D  false
2023-02-01 20:07:30.637  5760-5760  MULTI_WIND...CH_ENABLED de.astubenbord.paperless_mobile      D  false
2023-02-01 20:07:30.637  5760-5760  IS_CTS_MODE             de.astubenbord.paperless_mobile      D  false
2023-02-01 20:07:30.637  5760-5760  MULTI_WIND...CH_ENABLED de.astubenbord.paperless_mobile      D  false
2023-02-01 20:07:30.641  5760-5760  DecorView[]             de.astubenbord.paperless_mobile      D  getWindowModeFromSystem  windowmode is 1
2023-02-01 20:07:30.710  5760-5788  ResourceExtractor       de.astubenbord.paperless_mobile      I  Found extracted resources res_timestamp-15-1675278349228
2023-02-01 20:07:30.733  5760-5760  AdrenoGLES-0            de.astubenbord.paperless_mobile      I  QUALCOMM build                   : 820d4a4028, I5580630f49
                                                                                                    Build Date                       : 11/04/21
                                                                                                    OpenGL ES Shader Compiler Version: EV031.32.02.16
                                                                                                    Local Branch                     : 
                                                                                                    Remote Branch                    : 
                                                                                                    Remote Branch                    : 
                                                                                                    Reconstruct Branch               : 
2023-02-01 20:07:30.733  5760-5760  AdrenoGLES-0            de.astubenbord.paperless_mobile      I  Build Config                     : S P 10.0.7 AArch64
2023-02-01 20:07:30.733  5760-5760  AdrenoGLES-0            de.astubenbord.paperless_mobile      I  Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2023-02-01 20:07:30.739  5760-5760  AdrenoGLES-0            de.astubenbord.paperless_mobile      I  PFP: 0x016ee190, ME: 0x00000000
2023-02-01 20:07:30.827  5760-5760  aperless_mobil          de.astubenbord.paperless_mobile      W  Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (unsupported,test-api, reflection, allowed)
2023-02-01 20:07:30.827  5760-5760  aperless_mobil          de.astubenbord.paperless_mobile      W  Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (unsupported, reflection, allowed)
2023-02-01 20:07:30.827  5760-5760  aperless_mobil          de.astubenbord.paperless_mobile      W  Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (unsupported, reflection, allowed)
2023-02-01 20:07:30.827  5760-5760  aperless_mobil          de.astubenbord.paperless_mobile      W  Accessing hidden method Landroid/util/LongArray;->get(I)J (unsupported, reflection, allowed)
2023-02-01 20:07:30.849  5760-5760  Activity                de.astubenbord.paperless_mobile      W  PerfMonitor: Slow Operation: Activity de.astubenbord.paperless_mobile/com.example.paperless_mobile.MainActivity onStart took 164ms
2023-02-01 20:07:30.889  5760-5760  DecorView[]             de.astubenbord.paperless_mobile      D  getWindowModeFromSystem  windowmode is 1
2023-02-01 20:07:30.889  5760-5760  DecorView[]             de.astubenbord.paperless_mobile      D  updateDecorCaptionStatus displayWindowDecor is false
2023-02-01 20:07:30.902  5760-5760  Looper                  de.astubenbord.paperless_mobile      W  PerfMonitor looperActivity : package=de.astubenbord.paperless_mobile/com.example.paperless_mobile.MainActivity time=0ms latency=616ms running=0ms  procState=-1  historyMsgCount=4 (msgIndex=3 wall=263ms seq=3 running=211ms runnable=22ms io=10ms h=android.app.ActivityThread$H w=110) (msgIndex=4 wall=346ms seq=4 running=218ms runnable=36ms io=30ms h=android.app.ActivityThread$H w=159)
2023-02-01 20:07:30.924  5760-5806  flutter                 de.astubenbord.paperless_mobile      I  The Dart VM service is listening on http://127.0.0.1:37233/NYQlNCe-Wug=/
2023-02-01 20:07:30.991  5760-5760  SurfaceView             de.astubenbord.paperless_mobile      D  UPDATE null, mIsCastMode = false
2023-02-01 20:07:31.000  5760-5791  hw-ProcessState         de.astubenbord.paperless_mobile      D  Binder ioctl to enable oneway spam detection failed: Invalid argument
2023-02-01 20:07:31.012  5760-5760  SurfaceView             de.astubenbord.paperless_mobile      D  UPDATE Surface(name=SurfaceView[de.astubenbord.paperless_mobile/com.example.paperless_mobile.MainActivity])/@0xf39f354, mIsProjectionMode = false
2023-02-01 20:07:34.830  5760-5760  DecorView[]             de.astubenbord.paperless_mobile      D  onWindowFocusChanged hasWindowFocus true
2023-02-01 20:07:34.878  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  Adding received files to queue: 
2023-02-01 20:07:35.766  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.766  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.767  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/tags/?page=1&page_size=100000
2023-02-01 20:07:35.768  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:35.768  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.769  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.769  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/storage_paths/?page=1&page_size=100000
2023-02-01 20:07:35.769  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:35.769  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.769  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.769  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/correspondents/?page=1&page_size=100000
2023-02-01 20:07:35.769  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:35.887  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.887  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.887  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/saved_views/
2023-02-01 20:07:35.887  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:35.897  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.897  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.897  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/saved_views/
2023-02-01 20:07:35.897  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:35.898  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.898  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.898  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/ui_settings/
2023-02-01 20:07:35.898  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:35.898  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.898  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.898  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/document_types/?page=1&page_size=100000
2023-02-01 20:07:35.898  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:35.967  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.967  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.967  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/documents/4/thumb/
2023-02-01 20:07:35.967  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:35.967  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.967  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.967  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/documents/6/thumb/
2023-02-01 20:07:35.967  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:35.970  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:35.970  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:35.970  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/documents/?page=1&page_size=25&ordering=-created&truncate_content=true
2023-02-01 20:07:35.970  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:36.386  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:36.386  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:36.386  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/documents/11/thumb/
2023-02-01 20:07:36.386  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:37.077  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:37.077  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:37.077  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/documents/8/thumb/
2023-02-01 20:07:37.077  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:37.102  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:37.102  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:37.103  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/documents/9/thumb/
2023-02-01 20:07:37.103  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:39.398  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:39.398  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:39.398  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/documents/3/thumb/
2023-02-01 20:07:39.398  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:39.399  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:39.399  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:39.399  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/documents/10/thumb/
2023-02-01 20:07:39.399  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:39.414  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  
2023-02-01 20:07:39.414  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╔╣ Response ║ GET ║ Status: 200 OK
2023-02-01 20:07:39.414  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ║  https://paperless.######.##/api/documents/7/thumb/
2023-02-01 20:07:39.414  5760-5790  flutter                 de.astubenbord.paperless_mobile      I  ╚══════════════════════════════════════════════════════════════════════════════════════════╝
2023-02-01 20:07:42.985  5760-5760  InputMethodManager      de.astubenbord.paperless_mobile      D  showSoftInput() view=io.flutter.embedding.android.FlutterView{aa234a8 VFED..... .F....ID 0,0-1080,2270 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
2023-02-01 20:07:43.001  5760-5760  AssistStructure         de.astubenbord.paperless_mobile      I  Flattened final assist data: 492 bytes, containing 1 windows, 3 views
2023-02-01 20:07:43.047  5760-5760  InsetsController        de.astubenbord.paperless_mobile      D  show(ime(), fromIme=true)

```

**Comment by blitzdose** [comment]
The problem was so weird that I was searching for what could be the reason for it. And I actually found it!
The problem only occurs, when I have the Bitwarden (It's a password manager) "Assist" active. It is an option in the system Accessibility settings so that Bitwarden could automatically fill out passwords on the web. If I deactivate this feature all fields are working without a problem.

I think that's could be because Bitwaren is reading the text on the display in order to know where the password and username fields are and somehow this interferes with the package for the TypeAheadField.

**Comment by LUC4R4T0R** [comment]
I can confirm @blitzdose 's findings. Bitwarden was running while the problem occured. And it works correctly if I disable it.

Now it would be interesting to find out, if this issue is connected to the accesability features of android or if it only occurs with bitwarden.

**Comment by blitzdose** [comment]
> Now it would be interesting to find out, if this issue is connected to the accesability features of android or if it only occurs with bitwarden.

I do have some other accessibility services (even some that are for auto filling too Like bitwarden) but none of them triggered the issue. Seems very specific to Bitwarden

**Comment by astubenbord** [comment]
Interesting, thanks for having a look! I also use bitwarden but I don't have this problem. Maybe there is a way to prevent bitwarden from detecting the field as an autofill field. I'll have a look later this evening.

**Comment by astubenbord** [comment]
I just published a pre-release of the upcoming version, which is built with flutter 3.7. I don't think that this will fix the problem, but just try it out. 

[v2.0.0-pre](https://github.com/astubenbord/paperless-mobile/releases/tag/v2.0.0-pre)

**Comment by blitzdose** [comment]
> I just published a pre-release of the upcoming version, which is built with flutter 3.7. I don't think that this will fix the problem, but just try it out. 
> 
> [v2.0.0-pre](https://github.com/astubenbord/paperless-mobile/releases/tag/v2.0.0-pre)

No it sadly doesn't fix it. But I found out that other issue only applies to the bottom 4 options of the list. Everything above works fine.

**Comment by astubenbord** [comment]
You mean correspondent, document type, storage path and tags, right? This would make sense since all of them are built using the flutter_type_ahead library.

**Comment by blitzdose** [comment]
> You mean correspondent, document type, storage path and tags, right? This would make sense since all of them are built using the flutter_type_ahead library.

I tested it on correspondent, document type and storage path:
Correspondent:
The selection of an item from the list works without a problem, if no text is already in the text field. If I enter a single character, only the bottom 4 entries are not selectable. Everything above works

Document type and storage path:
On these fields it **always** doesn't work on the lower 4 entries. No matter if there is already text or not. It looks like there is an invisible area above the text field, that reaches from just above the field to the 4th entry from the bottom. Everything outside this box works fine:
![IMG_20230202_221023.jpg](https://user-images.githubusercontent.com/35041688/216450199-84fd9ec0-ff8d-4059-a4a3-5a1e082727b6.jpg)

**Comment by astubenbord** [comment]
Interesting. I think I'll try to implement the form builder widget myself using the latest version of flutter_type_ahead. Maybe this will fix the issue, although I'm a bit sceptical. I'll just update the files of release v2.0.0-pre once it's implemented.

**Comment by astubenbord** [comment]
I just updated it, could you try?

**Comment by blitzdose** [comment]
Still the same issue

**Comment by astubenbord** [comment]
Okay, unlucky. I guess there's not much I can do then except to rework the whole form field, which I'd rather not at the moment. So you're saying that it works as expected when turning Bitwarden off? Can assistive features be turned off selectively per-app? What android version are you on? Could be related to changes in android 13, I'll have hands on a pixel 7 the next days, I'll try if I can reproduce it there.

**Comment by blitzdose** [comment]
For me it works totally fine with the bitwarden "accessibility" option turned off. I can simply turn off this feature for bitwarden in the phones settings. I'm currently on Android 12 with MIUI (Xiaomi) 13

**Comment by astubenbord** [comment]
Just checked on a Pixel 3XL with android 12 and bitwarden and I can reproduce this now. Can also confirm that turning off accessibility features for bitwarden resolved it for me. Can I close this issue?

I guess I'll just add a troubleshooting section to the readme with this information. Thanks for your engagement in resolving this!

**Comment by blitzdose** [comment]
Yes the issue can be closed. I'm happy I could help
